### ISSUE TITLE
WarBender Instructions? [crashes]

### ISSUE THREAD

**Issue by Dorzalty** [int19h/WarBender#2]
Hello,

I recently came across your project via the forums, was very excited to see it, and decided to test it out. However, I do not understand how we run/use this program. I went ahead and downloaded the latest package and unzipped and tried to run the UI.exe, but it crashed. I'm assuming that I'm doing it wrong, that I'm missing a dependency or perhaps I unpacked it in the wrong place.

Are you planning on updating the github and or thread with instructions on how to use the program?

Thank you~

**Comment by int19h** [comment]
Sorry I didn't notice the report earlier!

Can you give a little bit more information on what exactly the error is?

Also, the app requires an up-to-date version of .NET. This should be present on most modern Windows versions, but just in case, try running the installer to see if you need to update it: https://www.microsoft.com/net/download/dotnet-framework-runtime

**Comment by Dorzalty** [comment]
Hello,

Yes, I have the most up to date version of .NET. As for the problem, it simply crashes without telling me anything helpful, but I took a screenshot regardless. It has sat collecting information for about an hour now.

https://i.imgur.com/jU30E9e.png

I have tried running it as Admin and setting it to Win7 compat, but that hasn't helped.

**Comment by int19h** [comment]
Try following the instructions [here](https://www.cyberlink.com/support/faq-content.do?id=10449)here to access your Event Log. It will most likely be the topmost event classified as error there.

**Comment by Dorzalty** [comment]
Hello,

I found one error for it in the log under "Application Error";

>Faulting application name: WarBender.UI.exe, version: 1.0.1.0, time stamp: 0x5b31f0e3
Faulting module name: unknown, version: 0.0.0.0, time stamp: 0x00000000
Exception code: 0xc0000005
Fault offset: 0x002daf4b
Faulting process id: 0x10b8
Faulting application start time: 0x01d44562d3344061
Faulting application path: C:\Users\Dorzalty\Tools\Mount & Blade\WarBender-1.0.1\WarBender.UI.exe
Faulting module path: unknown
Report Id: 11325649-b156-11e8-a180-5e208b1af9e8

**Comment by int19h** [comment]
Good to know! You were probably hitting the issue with Windows 7 that I fixed in 1.0.2, although I didn't realize there was an opportunity for it to happen at startup (and not just when opening a save).

Thank you for reporting the bug!
